# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a84cb0cce2f44566c534aa2a5f837e51464e88d275dd0c9f857c450555fa89ddd8c78770fe865bf87e64308bbba57b552e19c3903ece5d5edec017f2e340feaa

test:
  secret_key_base: bc4f7f93f645443dd8e63da2d2a59e86b2bff9c95df4e36c0d6793b9dc442e717ff87eb6e778c3611f1b5bfa7ca035132fba8065dac5dc78987be1e8bac45110

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
